In [1]:
import pandas as pd

In [2]:
file_name =  ".\logs_7-13march\storm-atlas-1\storm-frontend-server.log-20200311.gz"
#".\logs_7-13march\storm-atlas-1\storm-frontend-server.log-20200308.gz"

# ".\storm-frontend-20200307.log"
            
n_rows = 10000

In [3]:
frontend_0307 = pd.DataFrame()
frontend_0307 = pd.read_table(file_name,
                              sep = " -  ",
                              header= None,
                              nrows = n_rows,
                              engine = 'python'
                             )

In [4]:
frontend_0307

,0,1
0,03/10 03:11:05.860 Thread 43,INFO [d735165e-c414-4990-b1be-f47ccefde792]: p...
1,03/10 03:11:05.929 Thread 43,INFO [d735165e-c414-4990-b1be-f47ccefde792]: n...
2,03/10 03:11:05.938 Thread 43,INFO [d735165e-c414-4990-b1be-f47ccefde792]: R...
3,03/10 03:11:07.425 Thread 30,INFO [ce9dacb5-4059-444a-8787-35bdacfe834e]: p...
4,03/10 03:11:07.480 Thread 30,INFO [ce9dacb5-4059-444a-8787-35bdacfe834e]: R...
...,...,...
9995,03/10 03:29:19.769 Thread 10,INFO [90362710-bd5c-4b59-83f9-4f5c39544b64]: p...
9996,03/10 03:29:19.836 Thread 10,INFO [90362710-bd5c-4b59-83f9-4f5c39544b64]: n...
9997,03/10 03:29:19.839 Thread 10,INFO [90362710-bd5c-4b59-83f9-4f5c39544b64]: R...
9998,03/10 03:29:19.971 Thread 10,INFO [90362710-bd5c-4b59-83f9-4f5c39544b64]: n...
9999,03/10 03:29:19.990 Thread 10,INFO [90362710-bd5c-4b59-83f9-4f5c39544b64]: R...

In [5]:
temporary_file = './temporaryFile.csv'

In [6]:
frontend_0307[0].to_csv(temporary_file , header=False , index=False)

In [7]:
temporary1 = pd.read_table(temporary_file ,
              sep=None ,
              nrows=n_rows ,
              header=None ,
              engine='python',
              dtype = {0: str, 1: str, 2: str, 3: str} 
             )

temporary1[2] = temporary1[2] + ' ' + temporary1[3]

temporary1 = temporary1.drop(3, axis=1)

temporary1.columns = ["date", "time", "Thread"]

In [8]:
temporary1

       date          time     Thread
0     03/10  03:11:05.860  Thread 43
1     03/10  03:11:05.929  Thread 43
2     03/10  03:11:05.938  Thread 43
3     03/10  03:11:07.425  Thread 30
4     03/10  03:11:07.480  Thread 30
...     ...           ...        ...
9995  03/10  03:29:19.769  Thread 10
9996  03/10  03:29:19.836  Thread 10
9997  03/10  03:29:19.839  Thread 10
9998  03/10  03:29:19.971  Thread 10
9999  03/10  03:29:19.990  Thread 10

[10000 rows x 3 columns]

In [9]:
frontend_0307[1].to_csv(temporary_file , header=False , index=False)

In [10]:
temporary2 = pd.read_table(temporary_file ,
              sep= "]: " ,
              nrows=n_rows ,
              header=None ,
              engine='python',
              dtype = str
             )

In [11]:
frontend_0307 = pd.concat([temporary1, temporary2[0], temporary2[1]], axis=1)
frontend_0307 = frontend_0307.rename(columns={0:"Level", 1:"Content"})

frontend_0307.Level.to_csv(temporary_file , header=False , index=False)
temporary2 = pd.read_table(temporary_file ,
              sep= "[" ,
              nrows=n_rows ,
              header=None ,
              engine='python',
              dtype = str
             )
frontend_0307.Level = temporary2[0]
frontend_0307.insert(4, "Component", temporary2[1])

In [12]:
frontend_0307

,date,time,Thread,Level,Component,Content
0,03/10,03:11:05.860,Thread 43,INFO,d735165e-c414-4990-b1be-f47ccefde792,process_request : Connection from 2001:1458:20...
1,03/10,03:11:05.929,Thread 43,INFO,d735165e-c414-4990-b1be-f47ccefde792,ns1__srmReleaseFiles : Request: Release files....
2,03/10,03:11:05.938,Thread 43,INFO,d735165e-c414-4990-b1be-f47ccefde792,Result for request 'Release files' is 'SRM_SUC...
3,03/10,03:11:07.425,Thread 30,INFO,ce9dacb5-4059-444a-8787-35bdacfe834e,process_request : Connection from 2001:1458:20...
4,03/10,03:11:07.480,Thread 30,INFO,ce9dacb5-4059-444a-8787-35bdacfe834e,Request 'BOL status' from Client IP='2001:1458...
...,...,...,...,...,...,...
9995,03/10,03:29:19.769,Thread 10,INFO,90362710-bd5c-4b59-83f9-4f5c39544b64,process_request : Connection from 2001:1458:20...
9996,03/10,03:29:19.836,Thread 10,INFO,90362710-bd5c-4b59-83f9-4f5c39544b64,ns1__srmPing : Request: Ping. IP: 2001:1458:20...
9997,03/10,03:29:19.839,Thread 10,INFO,90362710-bd5c-4b59-83f9-4f5c39544b64,Result for request 'Ping' is 'SRM_SUCCESS'
9998,03/10,03:29:19.971,Thread 10,INFO,90362710-bd5c-4b59-83f9-4f5c39544b64,ns1__srmRm : Request: Rm. IP: 2001:1458:201:e3...
9999,03/10,03:29:19.990,Thread 10,INFO,90362710-bd5c-4b59-83f9-4f5c39544b64,Result for request 'Rm' is 'SRM_FAILURE'

In [13]:
frontend_0307.to_csv(".\storm-frontend-20200307.txt", index=False)

# frontend_0307 = frontend_0307.unstack(level=2) 
# facendo riferimento all'indice classe divide il data frame in tante colonne qanti sono i valori di del livello 0 ossia 'class'
# unstack funziona solo per dividere l'indice

from io import StringIO

data = pd.read_table(StringIO(frontend_0307[2][2]), sep=None, header = None)